-- Ausgearbeitete Programmpunkte zur Erprobung von req-003 fuer die drei
-- Reisen aus migrations/0002_seed_demo_data.sql.
-- Gestrichen mit req-064: Migrationen legen keine Reisedaten mehr an, damit
-- eine frische Umgebung leer ist. Verloren sind die Daten nicht -- sie
-- stehen in seed/demo-daten.sql und werden nur noch ausdruecklich
-- eingespielt (`npm run seed:demo` fuer eine frische dev-Umgebung,
-- tests/test-db.ts fuer die Testsuite).
--
-- Die Datei bleibt mit ihrer Nummer stehen: bereits eingespielte Umgebungen
-- fuehren sie deshalb nicht erneut aus, und ihre Daten bleiben unberuehrt
-- (siehe delivery/devops.md).
